crystal:
  seg_chan: 'ChS2-T1'
  snr_thresh: 8

  int_chan:
    - 'ChS1-T2'
    - 'ChS2-T1'

vessel:
  chan: 'Ch2-T2'
  seg_scale: 0.5
  thr: [2, 5]
  sigma: 3
  min_size: 1000


assemble:
  vol_thr: 100
  low_pct: 1
  high_pct: 99
