paths:
  image: D:\Zuohan\Z9\raw
  crystal: D:\Zuohan\Z9\seg

crystal:
  seg_chan: 'ChS2-T1'
  snr_thresh: 8

  dog_sigma: 1.
  gamma: .7
  spot_sigma: 1.
  outline_sigma: 1.

  int_chan:
    - 'ChS1-T2'
    - 'ChS2-T1'

vessel:
  chan: 'Ch2-T2'
  seg_scale: 0.5
  thr: [3, 5]


assemble:
  vol_thr: 500
  low_pct: 1
  high_pct: 99
